### ISSUE TITLE
Add PR and workflow links to releases

### ISSUE THREAD

**Issue by orzechow** [KIT-MRT/arbitration_graphs#80]
It would be great, if our releases pointed to the corresponding PR and the GitHub workflow that created the release.

I'd imagine sth. like this for e.g. [v0.3.0](https://github.com/KIT-MRT/arbitration_graphs/releases/tag/v0.3.0)

<details><summary>Current v0.3.0 release page</summary>

This adds download links to the latest debian packages to our GitHub Page.
It only hides the github and download buttons on other pages (like tutorial etc), to reduce distractions on these.

![image](https://github.com/user-attachments/assets/f462659b-920f-4b7a-bc59-556a33028454)

</details> 

<details><summary>Ideal v0.3.0 release page</summary>

This adds download links to the latest debian packages to our GitHub Page.
It only hides the github and download buttons on other pages (like tutorial etc), to reduce distractions on these.

![image](https://github.com/user-attachments/assets/f462659b-920f-4b7a-bc59-556a33028454)

This release is based on #76 and has been published by release job [11908462648](https://github.com/KIT-MRT/arbitration_graphs/actions/runs/11908462648).

</details> 

@ll-nick What do you think?

**Comment by ll-nick** [comment]
Yes, especially the PR number would be very helpful.
According to chatGPT, this is how we would have to adjust the release action:
```
      - name: Create Release        
        uses: ncipollo/release-action@v1        
        with:          
          artifacts: "/tmp/artifacts/release/*"          
          tag: ${{ needs.compute-version.outputs.new_tag }}          
          body: |
            ${{ github.event.pull_request.body }}  

            This release is based on #${{ github.event.pull_request.number }} and has been published by release job [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
```

I checked and these github variables actually exist. I have not tested any of it yet and will work on the tutorial first, so I'll just leave this here for future reference.
